services:
  app:
    build: .
    working_dir: /e2e
    command: ["tail", "-f", "/dev/null"]

    environment:
      - CI=true

    volumes:
      - ./cypress/screenshots:/e2e/cypress/screenshots
      - ./cypress/videos:/e2e/cypress/videos
      - ./cypress/reports:/e2e/cypress/reports
      - ./logs:/e2e/logs
